### ISSUE TITLE
from bqplot.marks import Graph

### ISSUE THREAD

**Issue by itg-abby** [dmadeka/PyDataSeattle2017#3]
Hi, I can't find this import anywhere in the code as a class:

from bqplot.marks import Graph

 Also, it does not appear to be in the documentation anywhere. It is needed to run the Neural Net demo, which I was really impressed with by the way!! Hope you can help me resolve this, thanks.

**Comment by dmadeka** [comment]
Hi @itg-abby , the import is [here](https://github.com/bloomberg/bqplot/blob/master/bqplot/marks.py#L1320). Please update your version. For future reference, please use [the official documentation](bqplot.readthedocs.io).

**Comment by itg-abby** [comment]
Thanks for such a fast response!

Note that:
1) the 'Graph' class is not specifically mentioned in the docs 
2) the version of marks.py on GitHub is newer than the one that installs automatically with pip or Conda (version 0.9.0).

**Comment by dmadeka** [comment]
@itg-abby I just added them to the docs.

The current version is an alpha. you'd have to `pip install --pre`

**Comment by itg-abby** [comment]
@dmadeka many thanks,
I got everything running using the dev version of bqplot, except that the final VBox wouldn't draw the Neural Network.
I could run the VBox with just the 'controls' and it would create the template sliders and buttons.

I did not change any of the cells, any thoughts?

Best

**Comment by dmadeka** [comment]
Please check the browser console to see errors and paste them here. If you install from pip ensure that you enable the extensions, otherwise bqplot will not work
