### ISSUE TITLE
NN Visualization Does not Display

### ISSUE THREAD

**Issue by itg-abby** [dmadeka/PyDataSeattle2017#4]
I cannot get the final Neural Network visualization in the demo to display.
- bqplot is working and plots all other displays
- No errors are being sent to the console. 
- I can run all the other parts of the demo successfully.

Are there any additional dependencies or extensions that I need to run specifically for the Neural Net visualization?

In the very last lines of the notebook, this is this line I want to make the display:
VBox([controls, nn], layout=Layout(min_height='1000px')) 

It does not create a display, however I can get the template at least from running this simplification (I just removed the 'nn'):
VBox([controls], layout=Layout(min_height='1000px')) 

Thanks!

**Comment by dmadeka** [comment]
Please paste your versions, browser, details. I am not able to recreate
this bug. Please paste the console output as well. This was the same thing I said in your last issue

**Comment by itg-abby** [comment]
Apologies, I thought the latest version was 0.9.0.
After updating to 0.10.0a3 it worked!

Also, the Readme in this repo says you only need >= 0.9.0
